### ISSUE TITLE
>=pciutils-3.11.1 fail to build with musl-1.2.5: sysfs.c:457:53: error: call to undeclared function 'basename'

### ISSUE THREAD

**Issue by ernsteiswuerfel** [pciutils/pciutils#182]
pciutils-3.11.1 and current 3.12.0 fail to build on musl-1.2.5 systems:
```
[...]
clang -Os -march=x86-64-v2 -pipe -Wall -W -Wno-parentheses -Wstrict-prototypes -Wmissing-prototypes -fPIC -fvisibility=hidden  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE  -c -o sysfs.o sysfs.c
sysfs.c:457:53: error: call to undeclared function 'basename'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  457 |           pci_set_property(d, PCI_FILL_IOMMU_GROUP, basename(group_link));
      |                                                     ^
sysfs.c:457:53: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'char *' [-Wint-conversion]
  457 |           pci_set_property(d, PCI_FILL_IOMMU_GROUP, basename(group_link));
      |                                                     ^~~~~~~~~~~~~~~~~~~~
./internal.h:131:58: note: passing argument to parameter 'value' here
  131 | char *pci_set_property(struct pci_dev *d, u32 key, char *value);
      |                                                          ^
2 errors generated.
make[1]: *** [<builtin>: sysfs.o] Error 1
```
This is Gentoo downstream bugreport #[926337](https://bugs.gentoo.org/926337).

Build log attached.
[pciutils-3.12.0:20240513-200212.log](https://github.com/pciutils/pciutils/files/15300191/pciutils-3.12.0.20240513-200212.log)

**Comment by drujd** [comment]
I am having this problem ONLY with GCC 14 - I can compile without problems with GCC 13.

**Comment by ernsteiswuerfel** [comment]
Compiler on this system was CLANG 18.1.5.

**Comment by gollux** [comment]
Hopefully fixed by commit 89cb2ae87236604b0e8ededd0fd7d9425c2d8cb6. Could you please test it?

**Comment by ernsteiswuerfel** [comment]
Thanks! The patch fixes the 3.12.0 build for musl-1.2.5 and does not harm 3.10.0.
